### ISSUE TITLE
Junit Report data is lost when multiple workflow run with this action

### ISSUE THREAD

**Issue by orestesgaolin** [ashley-taylor/junit-report-annotations-action#21]
I have multiple workflows configured for PRs, each can be triggered depending on the files changed in the PR.

Unfortunately the Junit Results annotations are present only in the first workflow and they are not visible in any other. All of them have very similar workflow files (with slight changes to paths)
![image](https://user-images.githubusercontent.com/16854239/89565856-75ca4f00-d81f-11ea-9462-aad06ee0b0da.png)

The results are shown correctly if there's only 1 workflow triggered that contains junit-report-annotations-action

Sample workflow.yaml:

```yaml
name: user_repository

on:
  pull_request:
    paths:
      - "packages/user_repository/**"
      - ".github/workflows/user_repository.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/u.....y

    runs-on: ubuntu-latest

    container:
      image: google/dart:2.8.4

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pub get

      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test

      - name: Check TODOs
        run: ../../tool/check_todos.sh .

      - name: Run tests
        run: pub run test --reporter json > test.log

      - name: Convert to junit
        run: |
          pub global activate junitreport
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          cat test.log
          cat test.log | tojunit > TEST.xml
        if: always()

      - uses: ashley-taylor/junit-report-annotations-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/TEST.xml"
          includeSummary: true
        if: always()

      - name: Run tests with coverage
        run: pub run test_coverage

      - name: Publish Coverage
        shell: bash
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

      - name: Check Code Coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: packages/u.....y/coverage/lcov.info
```

I can share more info via DM/Slack/email
