### ISSUE TITLE
Junit tests result passed but can not identify github check run id

### ISSUE THREAD

**Issue by AleksiUu** [ashley-taylor/junit-report-annotations-action#25]
Getting the following when trying to run junit-report-annotations-action:
```
Junit tests result passed but can not identify github check run id.
Can happen when performing a pull request from a forked repository.
```
Any ideas how to fix it or someway I could provide run id for the job? Tests are running inside Docker container.

**Comment by benc-uk** [comment]
Same problem
My step looks like this
```
      - uses: ashley-taylor/junit-report-annotations-action@1.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./src/test-results.xml
```
